### ISSUE TITLE
Git repository initialization

### ISSUE THREAD

**Issue by ZamboniMarco99** [baggiponte/chef#1]
`install` rule expect the project to be a git repository.

Error message:
```
An error has occurred: FatalError: git failed. Is it installed, and are you in a Git repository directory?
Check the log at /Users/marco/.cache/pre-commit/pre-commit.log
error: Recipe `install` failed with exit code 1
```

`config` rule expect a git remote to be configured

Error message:
```
error: No such remote 'origin'
 (y/n): y
/var/folders/53/k45zpdwx48b6vclybwb7jby00000gn/T/justp3lI8o/ensure-repo:189: not an identifier: A repo with this name already exists. Do you want to add it as a remote
error: Recipe `ensure-repo` failed with exit code 1
error: Recipe `config` failed with exit code 1
```

Possible fixes: 
1. document and ask the user to do it: something like adding `git init && git remote add origin your-repo` in the readme before the `just init` step
2. Let just perform those command (it is even indicated in [this comment](https://github.com/baggiponte/chef/blob/main/%7B%7B%20cookiecutter.__repo_name%20%7D%7D/justfile#L8)). The justfile at the root of this repo [does something like this](https://github.com/baggiponte/chef/blob/main/justfile#L13)

**Comment by baggiponte** [comment]
Ciao Marco, thanks for spotting this! 

> Let just perform those command (it is even indicated in [this comment](https://github.com/baggiponte/chef/blob/main/%7B%7B%20cookiecutter.__repo_name%20%7D%7D/justfile#L8)). The justfile at the root of this repo [does something like this](https://github.com/baggiponte/chef/blob/main/justfile#L13)

Indeed, I had that included but not execute in the cookiecutter's justfile. This should have been fixed with a3830a2, would you fancy trying if it works?

**Comment by baggiponte** [comment]
@ZamboniMarco99 sorry for the ping, would you mind checking if this works so I can close the issue? 😊

**Comment by ZamboniMarco99** [comment]
@baggiponte `just init` creates the local repository correctly, but `just install` (which, if I understood correctly, is an alternative if I don't want the github CI) still doesn't.

Also, `just init` fails later as there is a bug in the pre-commit configuration file where the hook for mypy doesn't have a name:
```
Installing pre-commit hooks...
pre-commit installed at .git/hooks/pre-commit
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: repos
==> At Repository(repo='local')
==> At key: hooks
==> At Hook(id='mypy')
=====> Missing required key: name
Check the log at /Users/marco/.cache/pre-commit/pre-commit.log
error: Recipe `install` failed on line 16 with exit code 1
```

**Comment by baggiponte** [comment]
> Also, just init fails later as there is a bug in the pre-commit configuration file where the hook for mypy doesn't have a name

Oh yes this is being addressed in #5. I will look into `just install`. I did not think of that as an alternative to CI, but a way to install all packages an pre-commit hooks. It should be a "development-oriented" setup.

**Comment by ZamboniMarco99** [comment]
> I did not think of that as an alternative to CI, but a way to install all packages an pre-commit hooks. It should be a "development-oriented" setup.

I was reading the README that says:
> Install all default dependencies and setup the GitHub secrets to run the CI/CD pipelines, run the following just recipe:
`just init`
> For this command to execute successfully, you need to have [pdm](https://pdm.fming.dev/latest/#installation) and the [GitHub CLI](https://github.com/cli/cli#installation) installed.
>
> This recipe will set three GitHub secrets:
>
> PDM_PUBLISH_REPO: the URL to publish your package to.
> PDM_PUBLISH_USERNAME: the username of the account used to publish the package.
> PDM_PUBLISH_PASSWORD: the authentication token.
> f you do not want to configure CI/CD on GitHub, you can simply run the following:
>
> `just install`
> This will only install the dev dependencies.

**Comment by baggiponte** [comment]
OH lol I might have removed that. Thanks for spotting that out, will need to fix that too.

**Comment by technosoft-admin** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @sparfenyuk, @jgrugru, @EasonLyon, @ycchen1989, @mhr, @g-tejas, @seangelb, @andersonfreitas, @Lucien-Yang, @rickycheng0607, @trongvnau, @zdomokos, @pjendrusik, @zhaoxing-zstar, @Smally, @sqr00t, @joeleong, @randomwalker42, @thookham, @jieyujing

**Comment by technosoft-admin** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @rambda, @twkim112, @keithtmccartney, @iloveopenworld, @XieXiaonan, @celticman3, @briangu, @i-aztec, @MonkeyDoug, @ymzhu99, @ajikmr, @kivo360, @7Adarshraj, @wgqzlj, @AutomationMike, @Liam-F, @uael, @ksanderer, @ivopetiz, @aidenstern

**Comment by uael** [comment]
@baggiponte please remove above phishing.

**Comment by baggiponte** [comment]
Reported as well. Thanks.
